#web:
#    image: nginx:latest
#    ports:
#        - "80:80"
#    links:
#        - php
#    volumes:
#        - ./code:/code
#        - ./site.conf:/etc/nginx/conf.d/default.conf
#php:
#    image: php:fpm
#    volumes:
#        - ./code:/code

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
  - mysqldata:/var/lib/mysql

php:
  build: .
  dockerfile: Dockerfile.fpm
  links:
  - mysql
  environment:
    DB_HOST: mysql

nginx:
  build: .
  dockerfile: Dockerfile.nginx
  ports:
  - "80:80"
  links:
  - php
